### ISSUE TITLE
Changes to babel presets

### ISSUE THREAD

**Issue by cklmercer** [JeffreyWay/laravel-elixir-vue#3]
Not sure what exactly is going on, but I've been fighting bugs all morning.

I installed a fresh copy of Laravel 5.3, installed npm modules, and ran gulp.. The following is the resulting error..

```
[17:47:20] Starting 'webpack'...
{ [Error: ./~/babel-loader!./~/vue-loader/lib/selector.js?type=script&index=0!./resources/assets/js/components/Example.vue
Module build failed: Error: Cannot remove "babel-plugin-transform-es2015-modules-commonjs" from the plugin list.
    at Object.<anonymous> (/home/vagrant/Code/test.dev/node_modules/babel-preset-es2015-webpack/index.js:35:11)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at /home/vagrant/Code/test.dev/node_modules/babel-core/lib/transformation/file/options/option-manager.js:324:15
    at Array.map (native)
    at OptionManager.resolvePresets (/home/vagrant/Code/test.dev/node_modules/babel-core/lib/transformation/file/options/option-manager.js:305:20)
 @ ./resources/assets/js/components/Example.vue 2:17-130
 @ ./resources/assets/js/app.js]
  message: './~/babel-loader!./~/vue-loader/lib/selector.js?type=script&index=0!./resources/assets/js/components/Example.vue\nModule build failed: Error: Cannot remove "babel-plugin-transform-es2015-modules-commonjs" from the plugin list.\n    at Object.<anonymous> (/home/vagrant/Code/test.dev/node_modules/babel-preset-es2015-webpack/index.js:35:11)\n    at Module._compile (module.js:413:34)\n    at Object.Module._extensions..js (module.js:422:10)\n    at Module.load (module.js:357:32)\n    at Function.Module._load (module.js:314:12)\n    at Module.require (module.js:367:17)\n    at require (internal/module.js:20:19)\n    at /home/vagrant/Code/test.dev/node_modules/babel-core/lib/transformation/file/options/option-manager.js:324:15\n    at Array.map (native)\n    at OptionManager.resolvePresets (/home/vagrant/Code/test.dev/node_modules/babel-core/lib/transformation/file/options/option-manager.js:305:20)\n @ ./resources/assets/js/components/Example.vue 2:17-130\n @ ./resources/assets/js/app.js',
  showStack: false,
  showProperties: true,
  plugin: 'webpack-stream',
  __safety: { toString: [Function: bound ] } }
```

Here are some related issues.

Related issue #1: https://github.com/gajus/babel-preset-es2015-webpack/issues/10
Related issue #2: https://github.com/gajus/babel-preset-es2015-webpack/issues/14

I've created a pull request which I believe resolves this.

**Comment by cklmercer** [comment]
I installed a fresh copy of Laravel 5.3, installed npm modules, and ran gulp.. The following is the resulting error..

```
[17:47:20] Starting 'webpack'...
{ [Error: ./~/babel-loader!./~/vue-loader/lib/selector.js?type=script&index=0!./resources/assets/js/components/Example.vue
Module build failed: Error: Cannot remove "babel-plugin-transform-es2015-modules-commonjs" from the plugin list.
    at Object.<anonymous> (/home/vagrant/Code/test.dev/node_modules/babel-preset-es2015-webpack/index.js:35:11)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at /home/vagrant/Code/test.dev/node_modules/babel-core/lib/transformation/file/options/option-manager.js:324:15
    at Array.map (native)
    at OptionManager.resolvePresets (/home/vagrant/Code/test.dev/node_modules/babel-core/lib/transformation/file/options/option-manager.js:305:20)
 @ ./resources/assets/js/components/Example.vue 2:17-130
 @ ./resources/assets/js/app.js]
  message: './~/babel-loader!./~/vue-loader/lib/selector.js?type=script&index=0!./resources/assets/js/components/Example.vue\nModule build failed: Error: Cannot remove "babel-plugin-transform-es2015-modules-commonjs" from the plugin list.\n    at Object.<anonymous> (/home/vagrant/Code/test.dev/node_modules/babel-preset-es2015-webpack/index.js:35:11)\n    at Module._compile (module.js:413:34)\n    at Object.Module._extensions..js (module.js:422:10)\n    at Module.load (module.js:357:32)\n    at Function.Module._load (module.js:314:12)\n    at Module.require (module.js:367:17)\n    at require (internal/module.js:20:19)\n    at /home/vagrant/Code/test.dev/node_modules/babel-core/lib/transformation/file/options/option-manager.js:324:15\n    at Array.map (native)\n    at OptionManager.resolvePresets (/home/vagrant/Code/test.dev/node_modules/babel-core/lib/transformation/file/options/option-manager.js:305:20)\n @ ./resources/assets/js/components/Example.vue 2:17-130\n @ ./resources/assets/js/app.js',
  showStack: false,
  showProperties: true,
  plugin: 'webpack-stream',
  __safety: { toString: [Function: bound ] } }
```
